version: '3.7'

networks:
  mynetwork:
    name: mynetwork
    driver: bridge

volumes:
  shared-content:

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mynetwork


  dropwizard:
    build: .
    container_name: dropwizard
    depends_on:
      - mongodb
    volumes:
      - ./target/LearnDataScience-1.0-SNAPSHOT.jar:/dropwizard/LearnDataScience-1.0-SNAPSHOT.jar
      - ./example.yml:/dropwizard/example.yml
    working_dir: /dropwizard
    ports:
      - "8090:8080"
      - "8091:8081"
    networks:
      - mynetwork

