FROM openjdk:11

RUN apt-get update && \
apt-get install -y python3 
# COPY --from=python:3.6 / /

ADD target/LearnDataScience-1.0-SNAPSHOT.jar /dropwizard/LearnDataScience-1.0-SNAPSHOT.jar
ADD example.yml /dropwizard/example.yml

EXPOSE 8080

WORKDIR /dropwizard/
CMD ["java", "-jar", "LearnDataScience-1.0-SNAPSHOT.jar", "server", "example.yml"]