apiVersion: v1
kind: Namespace
metadata:
  name: default

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: harness-delegate-cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Secret
metadata:
  name: default-proxy
  namespace: default
type: Opaque
data:
  # Enter base64 encoded username and password, if needed
  PROXY_USER: ""
  PROXY_PASSWORD: ""

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    harness.io/app: default
    harness.io/account: uonchb
    harness.io/name: default
  # Name must contain the six letter account identifier: uonchb
  name: default-uonchb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      harness.io/app: default
      harness.io/account: uonchb
      harness.io/name: default
  serviceName: ""
  template:
    metadata:
      labels:
        harness.io/app: default
        harness.io/account: uonchb
        harness.io/name: default
    spec:
      containers:
      - image: harness/delegate:latest
        imagePullPolicy: Always
        name: harness-delegate-instance
        resources:
          limits:
            cpu: "1"
            memory: "8Gi"
        readinessProbe:
          exec:
            command:
              - test
              - -s
              - delegate.log
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
              - bash
              - -c
              - '[[ -e /opt/harness-delegate/msg/data/watcher-data && $(($(date +%s000) - $(grep heartbeat /opt/harness-delegate/msg/data/watcher-data | cut -d ":" -f 2 | cut -d "," -f 1))) -lt 300000 ]]'
          initialDelaySeconds: 240
          periodSeconds: 10
          failureThreshold: 2
        env:
        - name: ACCOUNT_ID
          value: 9u5OnCHBSr2b2K_QFN-0PQ
        - name: ACCOUNT_SECRET
          value: 716de78290d79fd35970b0da941e9ef5
        - name: MANAGER_HOST_AND_PORT
          value: https://app.harness.io/gratis
        - name: WATCHER_STORAGE_URL
          value: https://app.harness.io/public/free/freemium/watchers
        - name: WATCHER_CHECK_LOCATION
          value: current.version
        - name: REMOTE_WATCHER_URL_CDN
          value: https://app.harness.io/public/shared/watchers/builds
        - name: DELEGATE_STORAGE_URL
          value: https://app.harness.io
        - name: DELEGATE_CHECK_LOCATION
          value: delegatefree.txt
        - name: DEPLOY_MODE
          value: KUBERNETES
        - name: DELEGATE_NAME
          value: default
        - name: DELEGATE_PROFILE
          value: "cjj868RDQHi9lXeGrfcPIg"
        - name: PROXY_HOST
          value: ""
        - name: PROXY_PORT
          value: ""
        - name: PROXY_SCHEME
          value: ""
        - name: NO_PROXY
          value: ""
        - name: PROXY_MANAGER
          value: "true"
        - name: PROXY_USER
          valueFrom:
            secretKeyRef:
              name: default-proxy
              key: PROXY_USER
        - name: PROXY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: default-proxy
              key: PROXY_PASSWORD
        - name: POLL_FOR_TASKS
          value: "false"
        - name: HELM_DESIRED_VERSION
          value: ""
        - name: CF_PLUGIN_HOME
          value: ""
        - name: USE_CDN
          value: "true"
        - name: CDN_URL
          value: https://app.harness.io
        - name: JRE_VERSION
          value: 1.8.0_242
        - name: HELM3_PATH
          value: ""
        - name: HELM_PATH
          value: ""
      restartPolicy: Always
